### ISSUE TITLE
[BUG] TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by ThinhVu** [isaacs/node-tar#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1254" alt="Screenshot 2023-05-08 at 1 35 57 PM" src="https://user-images.githubusercontent.com/8122962/236895801-027e2537-a46f-4715-8a4f-90b935114910.png">

```
error /app/node_modules/bcrypt: Command failed.
Exit code: 7
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /app/node_modules/bcrypt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@14.21.3 | linux | x64
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: Class extends value undefined is not a constructor or null
node-pre-gyp ERR! stack     at Object.<anonymous> (/app/node_modules/@mapbox/node-pre-gyp/node_modules/tar/lib/read-entry.js:97:4)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:1114:14)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:979:32)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
node-pre-gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:1003:19)
node-pre-gyp ERR! stack     at require (internal/modules/cjs/helpers.js:107:18)
node-pre-gyp ERR! stack     at Object.<anonymous> (/app/node_modules/@mapbox/node-pre-gyp/node_modules/tar/lib/pack.js:27:19)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:1114:14)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
node-pre-gyp ERR! System Linux 4.9.0-14-amd64
node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /app/node_modules/bcrypt
node-pre-gyp ERR! node -v v14.21.3
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
```

### Expected Behavior

Build success without any error

### Steps To Reproduce

1. In this environment...
2. Npm install the latest bcrypt
3. yarn
4. See error...

### Environment

- npm: (not sure)
- Node: v14.21.3
- OS: Linux: node:14
- platform: Docker

**Comment by erdemozveren** [comment]
Im using node-pre-gyp for electron build too,and one of my pacakges dependant on "tar" as in this situation.I think it didnt include "tar" on build so installing with "npm install tar" fixed for me.

**Comment by isaacs** [comment]
What version of tar is this loading? Line 97 isn't a "class extends" expression, so something funky is going on.

Can you reproduce it locally? What are the steps to do so?

**Comment by miafoo** [comment]
@ThinhVu Make sure you don't copy your `node_modules` to the container (eg. create a `.dockerignore` and add `node_modules` to it). If that doesn't fix it then make sure you upgrade to the latest version of `tar` (`6.1.14` as of writing this). I had the same issue a couple of days ago when starting a new project and doing so fixed it for me.

**Comment by isaacs** [comment]
@ThinhVu It does look like your tar is getting a version of minipass it's not able to handle, but it should be getting minipass v4, unless your dependency resolution is messed up.

The line and file referenced doesn't make sense, though.  Line 97 of lib/read-entry.js is not a `class` expression.  It's `[SLURP] (ex, global) {`.  So something doesn't line up here.

In an environment where this is happening, please run `npm ls minipass tar` and share the output.

**Comment by isaacs** [comment]
The only way I can figure that this might be happening is if your package manager is giving `tar` a version of minipass that doesn't meet its stated dependency range.  If that's what's going on, idk what to tell you. I wrote a package manager that doesn't use that, it's called npm, I recommend using it, since it works.

**Comment by stoefln** [comment]
@isaacs I would like to reopen this. Running into the same issue. Here is the output of `npm ls minipass tar` you asked for:

```
└─┬ electron-builder-squirrel-windows@24.4.0
  └─┬ app-builder-lib@24.4.0
    ├─┬ @electron/rebuild@3.2.13
    │ ├─┬ node-gyp@9.4.0
    │ │ ├─┬ make-fetch-happen@11.1.1
    │ │ │ ├─┬ cacache@17.1.3
    │ │ │ │ ├─┬ fs-minipass@3.0.2
    │ │ │ │ │ └── minipass@5.0.0 deduped
    │ │ │ │ ├─┬ glob@10.2.7
    │ │ │ │ │ ├── minipass@5.0.0 deduped
    │ │ │ │ │ └─┬ path-scurry@1.9.2
    │ │ │ │ │   └── minipass@5.0.0 deduped
    │ │ │ │ ├─┬ minipass-collect@1.0.2
    │ │ │ │ │ └── minipass@3.3.6
    │ │ │ │ ├── minipass@5.0.0 deduped
    │ │ │ │ └── tar@6.1.15 deduped
    │ │ │ ├─┬ minipass-fetch@3.0.3
    │ │ │ │ ├─┬ minipass-sized@1.0.3
    │ │ │ │ │ └── minipass@3.3.6
    │ │ │ │ └── minipass@5.0.0 deduped
    │ │ │ ├─┬ minipass-flush@1.0.5
    │ │ │ │ └── minipass@3.3.6
    │ │ │ ├─┬ minipass-pipeline@1.2.4
    │ │ │ │ └── minipass@3.3.6
    │ │ │ ├── minipass@5.0.0
    │ │ │ └─┬ ssri@10.0.4
    │ │ │   └── minipass@5.0.0 deduped
    │ │ └── tar@6.1.15 deduped
    │ └── tar@6.1.15 deduped
    └─┬ tar@6.1.15
      ├─┬ fs-minipass@2.1.0
      │ └── minipass@3.1.5 deduped invalid: "^5.0.0" from node_modules/tar
      ├── minipass@3.1.5 invalid: "^5.0.0" from node_modules/tar
      └─┬ minizlib@2.1.2
        └── minipass@3.1.5
```
        
I am confused, can you make sense of it?

**Comment by stoefln** [comment]
I fixed the issue by running `npx npm-force-resolutions; npm i`. Now the dependencies looks like this:
```
└─┬ electron-builder@24.4.0
  └─┬ app-builder-lib@24.4.0
    ├─┬ @electron/rebuild@3.2.13
    │ └─┬ node-gyp@9.4.0
    │   └─┬ make-fetch-happen@11.1.1
    │     ├─┬ cacache@17.1.3
    │     │ ├─┬ fs-minipass@3.0.2
    │     │ │ └── minipass@5.0.0 deduped
    │     │ ├─┬ glob@10.2.7
    │     │ │ ├── minipass@5.0.0 deduped
    │     │ │ └─┬ path-scurry@1.9.2
    │     │ │   └── minipass@5.0.0 deduped
    │     │ ├─┬ minipass-collect@1.0.2
    │     │ │ └── minipass@3.3.6
    │     │ └── minipass@5.0.0 deduped
    │     ├─┬ minipass-fetch@3.0.3
    │     │ ├─┬ minipass-sized@1.0.3
    │     │ │ └── minipass@3.3.6
    │     │ └── minipass@5.0.0 deduped
    │     ├─┬ minipass-flush@1.0.5
    │     │ └── minipass@3.3.6
    │     ├─┬ minipass-pipeline@1.2.4
    │     │ └── minipass@3.3.6
    │     ├── minipass@5.0.0 deduped
    │     └─┬ ssri@10.0.4
    │       └── minipass@5.0.0 deduped
    └─┬ tar@6.1.15
      ├─┬ fs-minipass@2.1.0
      │ └── minipass@3.3.6
      ├── minipass@5.0.0
      └─┬ minizlib@2.1.2
        └── minipass@3.1.5
```
