### ISSUE TITLE
Error crashing my service

### ISSUE THREAD

**Issue by kikar** [isaacs/node-tar#396]
Managed to catch with `process.on("uncaughtException", err => {});`
```
TypeError: Cannot read properties of undefined (reading '0')
    at /Users/home/Documents/project/node_modules/tar/lib/path-reservations.js:60:30
    at Array.every (<anonymous>)
    at check (/Users/home/Documents/project/node_modules/tar/lib/path-reservations.js:60:18)
    at run (/Users/home/Documents/project/node_modules/tar/lib/path-reservations.js:66:29)
    at /Users/home/Documents/project/node_modules/tar/lib/path-reservations.js:113:24
    at Set.forEach (<anonymous>)
    at clear (/Users/home/Documents/project/node_modules/tar/lib/path-reservations.js:113:10)
    at /Users/home/Documents/project/node_modules/tar/lib/path-reservations.js:70:14
    at done (/Users/home/Documents/project/node_modules/tar/lib/unpack.js:590:7)
    at /Users/home/Documents/project/node_modules/tar/lib/unpack.js:709:7
 ```

**Comment by isaacs** [comment]
Can you reproduce this reliably, eg with a specific tarball that fails to unpack?

**Comment by kikar** [comment]
> Can you reproduce this reliably, eg with a specific tarball that fails to unpack?

Yes, every time

**Comment by isaacs** [comment]
Can I have that tarball, please?

**Comment by isaacs** [comment]
Will reopen when problematic tarball is provided.
