### ISSUE TITLE
[Bug] path-reservations accessing index of undefined array

### ISSUE THREAD

**Issue by maka-io** [isaacs/node-tar#406]
/Users/Development/app/node_modules/tar/lib/path-reservations.js:60
    return paths.every(q => q[0] === fn) &&
                             ^

TypeError: Cannot read properties of undefined (reading '0')
    at /Users/Development/app/node_modules/tar/lib/path-reservations.js:60:30
    at Array.every (<anonymous>)
    at check (/Users/Development/app/node_modules/tar/lib/path-reservations.js:60:18)
    at run (/Users/Development/app/node_modules/tar/lib/path-reservations.js:66:29)
    at /Users/Development/app/node_modules/tar/lib/path-reservations.js:113:24
    at Set.forEach (<anonymous>)
    at clear (/Users/Development/app/node_modules/tar/lib/path-reservations.js:113:10)
    at /Users/Development/app/node_modules/tar/lib/path-reservations.js:70:14
    at done (/Users/Development/app/node_modules/tar/lib/unpack.js:590:7)
    at /Users/Development/app/node_modules/tar/lib/unpack.js:709:7

Node.js v20.10.0

Attempting to extract the tar from meteor:
https://packages.meteor.com/bootstrap-link?arch=os.osx.x86_64&release=3.0-beta.7

**Comment by isaacs** [comment]
This will be fixed in v7.
